chore: comment out MumakPort tests in e2e script

diff --git a/test/e2e b/test/e2e
--- a/test/e2e
+++ b/test/e2e
@@ -310,21 +310,21 @@ if (( SLOT < NODE_SLOT )); then
     handle_error "UtxoRpcPort" "UtxoRpcPort is not in the chain tip"
 fi
 
-echo "Testing MumakPort ..."
-RESOURCE=$(create_port 'MumakPort' '"{\"network\":\"mainnet\",\"throughputTier\":\"0\"}"')
-if [ $? -ne 0 ]; then
-  handle_error "MumakPort" "Failed to create MumakPort"
-fi
-export PGUSER=$(echo "$RESOURCE" | jq -r '.records[0].spec' | jq -r '.username')
-export PGPASSWORD=$(echo "$RESOURCE" | jq -r '.records[0].spec' | jq -r '.password')
-SLOT=$(psql --dbname=cardano-mainnet --host=mumak-m0.demeter.run -c "select slot from blocks order by slot desc limit 1" -t)
-if [ $? -ne 0 ]; then
-  handle_error "MumakPort" "MumakPort validation failed"
-fi
-echo "Mumak slot: $SLOT"
-if (( SLOT < NODE_SLOT )); then
-    handle_error "MumakPort" "MumakPort is not in the chain tip"
-fi
+# echo "Testing MumakPort ..."
+# RESOURCE=$(create_port 'MumakPort' '"{\"network\":\"mainnet\",\"throughputTier\":\"0\"}"')
+# if [ $? -ne 0 ]; then
+#   handle_error "MumakPort" "Failed to create MumakPort"
+# fi
+# export PGUSER=$(echo "$RESOURCE" | jq -r '.records[0].spec' | jq -r '.username')
+# export PGPASSWORD=$(echo "$RESOURCE" | jq -r '.records[0].spec' | jq -r '.password')
+# SLOT=$(psql --dbname=cardano-mainnet --host=mumak-m0.demeter.run -c "select slot from blocks order by slot desc limit 1" -t)
+# if [ $? -ne 0 ]; then
+#   handle_error "MumakPort" "MumakPort validation failed"
+# fi
+# echo "Mumak slot: $SLOT"
+# if (( SLOT < NODE_SLOT )); then
+#     handle_error "MumakPort" "MumakPort is not in the chain tip"
+# fi
 
 echo "Testing DbSyncPort ..."
 RESOURCE=$(create_port 'DbSyncPort' '"{\"network\":\"mainnet\",\"throughputTier\":\"0\"}"')
