feat: added utxorpc test

diff --git a/test/e2e b/test/e2e
--- a/test/e2e
+++ b/test/e2e
@@ -157,6 +157,27 @@ node_port_expect() {
     exit 1
 }
 
+
+utxorpc_port_expect() {
+    local key=$1
+
+    for attempt in $(seq 1 $MAX_ATTEMPT); do
+        UTXO_SLOT=$(./grpcurl -H "dmtr-api-key: $key" -H 'content-type: application/grpc' mainnet.utxorpc-v0.demeter.run:443 utxorpc.v1alpha.query.QueryService.ReadParams | jq -r '.ledgerTip.slot')
+
+        if [[ -n "$UTXO_SLOT" ]]; then
+            echo "$UTXO_SLOT"
+            return 0
+        fi
+
+        sleep $SLEEP_DURATION
+    done
+
+    echo "Error: UtxoRpc is not ready after $MAX_ATTEMPT attempts."
+    finish 
+    exit 1
+}
+
+
 echo "Configuring environment ..."
 
 install_dependencies
@@ -197,6 +218,15 @@ SLOT="$(echo "$RESPONSE" | jq -r '.lastKnownTip.slot')"
 echo "Ogmios slot: $SLOT"
 if (( SLOT < NODE_SLOT )); then
     echo "Error: OgmiosPort is not in the chain tip"
+    finish 
+    exit 1
+fi
+
+RESOURCE=$(create_port 'UtxoRpcPort' '"{\"network\":\"mainnet\",\"throughputTier\":\"0\",\"operatorVersion\":\"1\"}"')
+SLOT=$(utxorpc_port_expect $(echo "$RESOURCE" | jq -r '.records[0].spec' | jq -r '.authToken'))
+echo "UtxoRpc slot: $SLOT"
+if (( SLOT < NODE_SLOT )); then
+    echo "Error: UtxoRpcPort is not in the chain tip"
     finish 
     exit 1
 fi
