chore: added job to create redpand topic after it is ready

diff --git a/test/expect b/test/expect
--- a/test/expect
+++ b/test/expect
@@ -3,7 +3,7 @@ tar -zxvf ./grpcurl_1.9.1_linux_x86_64.tar.gz grpcurl
 
 ATTEMPT=1
 MAX_ATTEMPT=6
-echo "Waiting for kafka to be ready..."
+echo "Waiting for kafka to be ready"
 while [ $ATTEMPT -lt $MAX_ATTEMPT ]; do
     pod_status=$(kubectl get pods -n demeter-kafka -o 'jsonpath={.items[*].status.conditions[?(@.type=="Ready")].status}' | grep True)
 
@@ -15,13 +15,20 @@ while [ $ATTEMPT -lt $MAX_ATTEMPT ]; do
         let ATTEMPT=ATTEMPT+1
     fi
 done
+if [ $ATTEMPT -eq $MAX_ATTEMPT ]; then
+    echo "Error: Kafka is not ready after $MAX_ATTEMPT attempts."
+    exit 1
+fi
 
+echo "Getting Auth0 access token"
 TOKEN=$(curl --verbose --request POST --url https://dev-dflg0ssi.us.auth0.com/oauth/token --header 'content-type: application/json' --data $TEST_CREDENTIAL | jq -r '.access_token')
+
+echo "Creating namespace"
 NODE_IP=$(kubectl get nodes -o jsonpath='{.items[0].status.addresses[?(@.type=="InternalIP")].address}')
-NAMESPACE=$(./grpcurl -plaintext -vv -H "Authorization: Bearer $TOKEN" -d '{"name": "New Namespace"}' "$NODE_IP":30950 demeter.ops.v1alpha.ProjectService.CreateProject | jq -r '.namespace')
+NAMESPACE=$(./grpcurl -plaintext -H "Authorization: Bearer $TOKEN" -d '{"name": "New Namespace"}' "$NODE_IP":30950 demeter.ops.v1alpha.ProjectService.CreateProject | jq -r '.namespace')
 
 ATTEMPT=1
-MAX_ATTEMPT=12
+MAX_ATTEMPT=6
 echo "Checking executation"
 while [ $ATTEMPT -lt $MAX_ATTEMPT ]; do
     if kubectl get namespace "$NAMESPACE" &> /dev/null; then
@@ -29,11 +36,10 @@ while [ $ATTEMPT -lt $MAX_ATTEMPT ]; do
         break
     else
         echo "Namespace $NAMESPACE not found. Retrying..."
-        sleep 2
+        sleep 5
         let ATTEMPT=ATTEMPT+1
     fi
 done
-
 if [ $ATTEMPT -eq $MAX_ATTEMPT ]; then
     echo "Error: Namespace $NAMESPACE not found after $MAX_ATTEMPT attempts."
     exit 1
